baseURL = "https://hiroyuki8823.net/"
languageCode = "jp-JP"
title = "hiroyuki+=1"
theme = "hugo_theme_robust"

googleAnalytics="UA-135065044-1"

[params]
  description = "１日ひとつだけ強くなろう"
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/prof_icon.jpg"
  name = "Hiroyuki nZk"
  description = "<p>都内の小さなSierでプログラマーやってます。</p><p>学習の成果とか読んだ本のアウトプットする場にしていきたい。</p><p>学習していること:JavaScript,Python,AWS,firebase</p>"
  facebook = "https://www.facebook.com/hiroyuki.nozaki.92"
  twitter = "https://twitter.com/H1r0yuk188231"
  github = "https://github.com/h1r0yuki8823"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
